spring:
  profiles:
    active: dev
  jmx:
    enabled: false
  jpa:
    show-sql: false
  redis:
    host: 192.168.1.142
    #host: localhost
    port: 6379

controller-config:
  enable:
    bo: true
    player: true

# System
server:
  servlet:
    context-path: /COFFEE
  port: 8080
